config/routes.rb
Rails.application.routes.draw do

  resources :asignacion, only: [:index, :create, :destory]

  devise_for :pacientes, path: 'pacientes', path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', registration: 'register', sign_up: 'cmon_let_me_in' }

  resources :asignacion do
    collection do
      get :get_medicos
    end
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/citum.rb
class Citum < ApplicationRecord
  belongs_to :paciente
  belongs_to :medico
end

app/models/medico.rb
class Medico < ApplicationRecord
end

app/models/paciente.rb
class Paciente < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/recurso.rb
class Recurso < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/asignacion_controller.rb
class AsignacionController < ApplicationController
  before_action :authenticate_paciente!
  def index
    @citum = Citum.new
  end

  def create

    medico = Medico.find(params[:citum]["medico"])
    @citum = Citum.new(medico: , paciente: current_paciente)
    if @citum.save
      redirect_to root_path
    else
      respond_to do |format|
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @citum.errors, status: :unprocessable_entity }
      end
    end
  end

  def get_medicos
    @target = params[:target]
    @medicos = Medico.where(horario: params[:hour])
    @medicos = @medicos.map { |medico| [medico.nombre, medico.id] }
    respond_to do |format|
      format.turbo_stream
    end
  end

end

app/controllers/paciente/confirmations_controller.rb
# frozen_string_literal: true

class Paciente::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/paciente/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Paciente::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/paciente/passwords_controller.rb
# frozen_string_literal: true

class Paciente::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/paciente/registrations_controller.rb
# frozen_string_literal: true

class Paciente::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  def new
    super
  end

  # POST /resource
  def create
    super
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  def after_sign_up_path_for(resource)
    redirect_to asignacion_index_path
  end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/paciente/sessions_controller.rb
# frozen_string_literal: true

class Paciente::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/paciente/unlocks_controller.rb
# frozen_string_literal: true

class Paciente::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/asignacion_helper.rb
module AsignacionHelper
end

app/helpers/header_helper.rb
module HeaderHelper
  def header_logeable
    if paciente_signed_in?
      render 'shared/header_login'
    else
      render 'shared/header'
    end
  end

end

app/views/asignacion/get_medicos.turbo_stream.erb
<%= turbo_stream.update @target do%>
  <%= options_for_select @medicos %>
<% end %>

app/views/asignacion/index.html.erb
<!-- component -->
<div class="flex items-center justify-center p-12 h-screen">
  <!-- Author: FormBold Team -->
  <!-- Learn More: https://formbold.com -->
  <div class="mx-auto w-full max-w-[550px]">
    <h1 class='text-lg'>Generacion de citas a nivel electronico</h1>
    <p>Aqui puedes consultar que medicos estan disponibles en tu horario preferido</p>
    <%= form_with(model: @citum, class: 'mx-auto w-full max-w-[550px]', url: asignacion_index_path, method: :post) do |f| %>
      <div data-controller='medicos'>
        <div class="mb-5">
          <%= f.label :horario, class:'mb-3 block text-base font-medium text-[#07074D]' %><br />
          <%= f.select :horario, (1..24).to_a, {promp: "Selecciona una hora"}, {class: 'w-full appearance-none rounded-md border border-[#e0e0e0] b
                          g-white py-3 px-6 text-base font-medium text-[#6B7280] outline-none 
                          focus:border-[#6A64F1] focus:shadow-md', data: {action: "change->medicos#change"}} %>
        </div>
        <div class="mb-5">
          <%= f.label :medico, class:'mb-3 block text-base font-medium text-[#07074D]' %><br />
          <%= f.select :medico, [], {}, {
                        class: 'w-full appearance-none rounded-md border border-[#e0e0e0] b
                        g-white py-3 px-6 text-base font-medium text-[#6B7280] outline-none 
                        focus:border-[#6A64F1] focus:shadow-md', data: {medicos_target: "medicoSelect"}}%>
        </div>
      </div>
      <div class="actions mt-3">
        <%= f.submit "Asignar", class:'w-full py-4 bg-blue-600 rounded-lg text-green-100 cursor-pointer' %>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Citologia</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <main>
      <%= header_logeable %>
      <%= yield %>
      <%= render 'shared/footer' %>
    </main>
  </body>
</html>

app/views/pages/about.html.erb
<!-- component -->
<div class="py-16 bg-white h-screen flex items-center">
  <div class="container m-auto px-6 text-gray-600 md:px-12 xl:px-6">
    <div class="space-y-6 md:space-y-0 md:flex md:gap-6 lg:items-center lg:gap-12">
      <div class="md:5/12 lg:w-5/12">
        <img src="https://tailus.io/sources/blocks/left-image/preview/images/startup.png" alt="image" loading="lazy" width="" height="">
      </div>
      <div class="md:7/12 lg:w-6/12">
        <h2 class="text-2xl text-gray-900 font-bold md:text-4xl">Nuestra Historia: Sembrando Salud</h2>
        <p class="mt-6 text-gray-600">Desde nuestros inicios como un proyecto académico en 2024, Citology ha sido impulsada por la pasión de transformar la atención médica. Nuestra visión era clara: crear una plataforma que conectara a pacientes con profesionales de la salud de manera más eficiente y accesible.</p>
        <p class="mt-4 text-gray-600"> Comenzamos con un equipo pequeño y un gran sueño. A través de grandes Hitos, hemos logrado construir una red de confianza que conecta a miles de personas con los cuidados que necesitan.</p>
      </div>
    </div>
  </div>
</div>

app/views/shared/_footer.html.erb
<!-- Footer -->
<footer class="bg-gray-800 pt-10 sm:mt-10 pt-10 w-full">
  <div class="max-w-6xl m-auto text-gray-800 flex flex-wrap justify-left">
    <!-- Col-1 -->
    <div class="p-5 w-1/2 sm:w-4/12 md:w-3/12">
      <!-- Col Title -->
      <div class="text-xs uppercase text-gray-400 font-medium mb-6">
        Getting Started
      </div>
      <!-- Links -->
      <a
                href="#"
                class="my-3 block text-gray-300 hover:text-gray-100 text-sm font-medium duration-700">
        Installation
      </a>
      <a
                href="#"
                class="my-3 block text-gray-300 hover:text-gray-100 text-sm font-medium duration-700">
        Release Notes
      </a>
      <a
                href="#"
                class="my-3 block text-gray-300 hover:text-gray-100 text-sm font-medium duration-700">
        Upgrade Guide
      </a>
    </div>
    <!-- Col-2 -->
    <div class="p-5 w-1/2 sm:w-4/12 md:w-3/12">
      <!-- Col Title -->
      <div class="text-xs uppercase text-gray-400 font-medium mb-6">
        Core Concepts
      </div>
      <!-- Links -->
      <a
                href="#"
                class="my-3 block text-gray-300 hover:text-gray-100 text-sm font-medium duration-700">
        Utility-First
      </a>
      <a
                href="#"
                class="my-3 block text-gray-300 hover:text-gray-100 text-sm font-medium duration-700">
        Responsive Design
      </a>
      <a
                href="#"
                class="my-3 block text-gray-300 hover:text-gray-100 text-sm font-medium duration-700">
        Hover, Focus, & Other States
      </a>
    </div>
    <!-- Col-3 -->
    <div class="p-5 w-1/2 sm:w-4/12 md:w-3/12">
      <!-- Col Title -->
      <div class="text-xs uppercase text-gray-400 font-medium mb-6">
        Customization
      </div>
      <!-- Links -->
      <a
                href="#"
                class="my-3 block text-gray-300 hover:text-gray-100 text-sm font-medium duration-700">
        Configuration
      </a>
      <a
                href="#"
                class="my-3 block text-gray-300 hover:text-gray-100 text-sm font-medium duration-700">
        Theme Configuration
      </a>
      <a
                href="#"
                class="my-3 block text-gray-300 hover:text-gray-100 text-sm font-medium duration-700">
        Breakpoints
      </a>
    </div>
    <!-- Col-3 -->
    <div class="p-5 w-1/2 sm:w-4/12 md:w-3/12">
      <!-- Col Title -->
      <div class="text-xs uppercase text-gray-400 font-medium mb-6">
        Community
      </div>
      <!-- Links -->
      <a
                href="#"
                class="my-3 block text-gray-300 hover:text-gray-100 text-sm font-medium duration-700">
        GitHub
      </a>
      <a
                href="#"
                class="my-3 block text-gray-300 hover:text-gray-100 text-sm font-medium duration-700">
        Discord
      </a>
      <a
                href="#"
                class="my-3 block text-gray-300 hover:text-gray-100 text-sm font-medium duration-700">
        Twitter
      </a>
      <a
                href="#"
                class="my-3 block text-gray-300 hover:text-gray-100 text-sm font-medium duration-700">
        YouTube
      </a>
    </div>
  </div>
  <!-- Copyright Bar -->
  <div class="pt-2">
    <div
            class="flex pb-5 px-3 m-auto pt-5 border-t border-gray-500 text-gray-400 text-sm flex-col md:flex-row max-w-6xl">
      <div class="mt-2">© Todos los derechos reservados 2024</div>
      <!-- Required Unicons (if you want) -->
      <div class="md:flex-auto md:flex-row-reverse mt-2 flex-row flex">
        <a href="#" class="w-6 mx-1">
          <i class="uil uil-facebook-f"></i>
        </a>
        <a href="#" class="w-6 mx-1">
          <i class="uil uil-twitter-alt"></i>
        </a>
        <a href="#" class="w-6 mx-1">
          <i class="uil uil-youtube"></i>
        </a>
        <a href="#" class="w-6 mx-1">
          <i class="uil uil-linkedin"></i>
        </a>
        <a href="#" class="w-6 mx-1">
          <i class="uil uil-instagram"></i>
        </a>
      </div>
    </div>
  </div>
</footer>

app/views/shared/_header.html.erb
    <header class="container">
        <!-- Navbar -->
        <nav
            class="flex justify-between md:justify-around py-4 bg-white/80 backdrop-blur-md shadow-md w-full px-10 fixed top-0 left-0 right-0 z-10 px-8 md:px-3">
            <!-- Logo Container -->
            <div class="flex items-center">
                <%= link_to  root_path do %>
                    <%= image_tag 'logo_medico.png', class: 'w-20' %>
                <% end %>
                
            </div>

            <!-- Links Section -->
            <div
                class="items-center md:space-x-8 
                    justify-center justify-items-start 
                    md:justify-items-center md:flex md:pt-2 
                    w-full left-0 top-16 px-5 md:px-10 py-3 
                    md:py-0 border-t md:border-t-0">
                
                <%= link_to 'Inicio', root_path, class: 'flex text-gray-600 hover:text-blue-500 cursor-pointer transition-colors duration-300' %>
                <%= link_to 'Sobre nosotros', page_path('about'), class: 'flex text-gray-600 hover:text-blue-500 cursor-pointer transition-colors duration-300' %>
                
            </div>

            <!-- Auth Links -->
            <div class="flex items-center space-x-5 hidden md:flex">
                <!-- Register -->
                <%= link_to  new_paciente_registration_path, class: 'flex text-gray-600 hover:text-blue-500 cursor-pointer transition-colors duration-300' do %>
                    <svg
                        class="fill-current h-5 w-5 mr-2 mt-0.5"
                        xmlns="http://www.w3.org/2000/svg"
                        xmlns:xlink="http://www.w3.org/1999/xlink"
                        version="1.1"
                        width="24"
                        height="24"
                        viewBox="0 0 24 24">
                        <path
                            d="M12 0L11.34 .03L15.15 3.84L16.5 2.5C19.75 4.07 22.09 7.24 22.45 11H23.95C23.44 4.84 18.29 0 12 0M12 4C10.07 4 8.5 5.57 8.5 7.5C8.5 9.43 10.07 11 12 11C13.93 11 15.5 9.43 15.5 7.5C15.5 5.57 13.93 4 12 4M12 6C12.83 6 13.5 6.67 13.5 7.5C13.5 8.33 12.83 9 12 9C11.17 9 10.5 8.33 10.5 7.5C10.5 6.67 11.17 6 12 6M.05 13C.56 19.16 5.71 24 12 24L12.66 23.97L8.85 20.16L7.5 21.5C4.25 19.94 1.91 16.76 1.55 13H.05M12 13C8.13 13 5 14.57 5 16.5V18H19V16.5C19 14.57 15.87 13 12 13M12 15C14.11 15 15.61 15.53 16.39 16H7.61C8.39 15.53 9.89 15 12 15Z" />
                    </svg>

                    Register
                <% end %>
        


                <!-- Login -->

                <%= link_to new_paciente_session_path, class:'flex text-gray-600 cursor-pointer transition-colors duration-300 font-semibold text-blue-600'  do%>
                <svg
                        class="fill-current h-5 w-5 mr-2 mt-0.5"
                        xmlns="http://www.w3.org/2000/svg"
                        xmlns:xlink="http://www.w3.org/1999/xlink"
                        version="1.1"
                        width="24"
                        height="24"
                        viewBox="0 0 24 24">
                        <path
                            d="M10,17V14H3V10H10V7L15,12L10,17M10,2H19A2,2 0 0,1 21,4V20A2,2 0 0,1 19,22H10A2,2 0 0,1 8,20V18H10V20H19V4H10V6H8V4A2,2 0 0,1 10,2Z" />
                    </svg>

                    ingreso
                <% end %>
                

                <a
                    class="">
                    
                </a>
            </div>

            <!-- Hamberger Menu -->
            <button
                class="w-10 h-10 md:hidden justify-self-end rounded-full hover:bg-gray-100">
                <svg
                    class="mx-auto"
                    xmlns="http://www.w3.org/2000/svg"
                    xmlns:xlink="http://www.w3.org/1999/xlink"
                    version="1.1"
                    width="24"
                    height="24"
                    viewBox="0 0 24 24">
                    <path d="M3,6H21V8H3V6M3,11H21V13H3V11M3,16H21V18H3V16Z" />
                </svg>
            </button>
        </nav>
    </header>

app/views/shared/_header_login.html.erb
<header class="container">
  <!-- Navbar -->
  <nav
            class="flex justify-between md:justify-around py-4 bg-white/80 backdrop-blur-md shadow-md w-full px-10 fixed top-0 left-0 right-0 z-10 px-8 md:px-3">
    <!-- Logo Container -->
    <div class="flex items-center">
      <%= link_to  root_path do %>
        <%= image_tag 'logo_medico.png', class: 'w-20' %>
      <% end %>
    </div>
    <!-- Links Section -->
    <div
                class="items-center md:space-x-8 
                    justify-center justify-items-start 
                    md:justify-items-center md:flex md:pt-2 
                    w-full left-0 top-16 px-5 md:px-10 py-3 
                    md:py-0 border-t md:border-t-0">
      <%= link_to 'Inicio', root_path, class: 'flex text-gray-600 hover:text-blue-500 cursor-pointer transition-colors duration-300' %>
      <%= link_to 'Sobre nosotros', page_path('about'), class: 'flex text-gray-600 hover:text-blue-500 cursor-pointer transition-colors duration-300' %>
      <%= link_to 'Citas', asignacion_index_path, class: 'flex text-gray-600 hover:text-blue-500 cursor-pointer transition-colors duration-300' %>
    </div>
    <!-- destroy session -->
    <%= button_to 'CERRAR SESION', destroy_paciente_session_path, class:'flex text-red-600 cursor-pointer transition-colors duration-300 font-semibold text-red-600', method: :delete %>
  </div>
  <!-- Hamberger Menu -->
  <button
                class="w-10 h-10 md:hidden justify-self-end rounded-full hover:bg-gray-100">
    <svg
                    class="mx-auto"
                    xmlns="http://www.w3.org/2000/svg"
                    xmlns:xlink="http://www.w3.org/1999/xlink"
                    version="1.1"
                    width="24"
                    height="24"
                    viewBox="0 0 24 24">
      <path d="M3,6H21V8H3V6M3,11H21V13H3V11M3,16H21V18H3V16Z" />
    </svg>
  </button>
</nav>
</header>